name: Production Release

on:
  push:
    branches: 
    - master
    
jobs:      
  unitTest:
   name: Run Unit tests
   runs-on: ubuntu-latest
  
   steps:
    - uses: actions/checkout@v2
    - run: bash ./gradlew test

  apk:
   needs: unitTest
   runs-on: ubuntu-latest
   steps:
     - name: Assemble app debug APK
       run: bash ./gradlew :github-actions-playground:assembleDebug --stacktrace
